safe: true
lsi: false
pygments: true
name: Pocket Linesman | Blog
description: The blog of the premier iOS app for Soccer/Football - Pocket Linesman. Replace your referee wallet and notebook with this premier iPhone app.
title: Pocket Linesman
url: http://www.pocketlinesman.com
appStoreLink: https://itunes.apple.com/us/app/pocket-linesman-referee-wallet/id712375993?ls=1&mt=8
appId: 712375993